# Generated by Django 5.1.4 on 2026-09-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaeducativa',
            name='respuesta_correcta',
            field=models.BooleanField(default=True, help_text='Marcar para Verdadero/Realidad. Desmarcar para Falso/Mito.', verbose_name='¿Es Verdadero/Realidad? (Solo Sesión 1 y 3)'),
        ),
        migrations.AlterField(
            model_name='preguntaeducativa',
            name='sesion',
            field=models.CharField(choices=[('S1', 'Sesión 1: Mitos vs Realidades'), ('S2', 'Sesión 2: Preguntas Clave (Selección Múltiple)'), ('S3', 'Sesión 3: Verdadero o Falso')], max_length=2, verbose_name='Sesión'),
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255, verbose_name='Texto de la Opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='prevencion.preguntaeducativa', verbose_name='Pregunta Asociada')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
            },
        ),
    ]
