# Generated by Django 5.1.4 on 2026-09-22 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0002_alter_preguntaeducativa_respuesta_correcta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevencion.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_usuarios', to='prevencion.preguntaeducativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_educativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'pregunta')},
            },
        ),
    ]
