# Generated by Django 5.1.4 on 2026-09-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0003_respuestausuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RespuestaUsuario',
        ),
    ]
