# Generated by Django 5.1.4 on 2026-10-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0005_cargar_preguntas_iniciales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalisisEcografia',
        ),
    ]
